In [ ]:
# Lab - Numpy in a nutshell
#Introduction
#두 번째 LAB은 Numpy 입니다. Numpy 강의는 사실 그냥 보고만 있으면, 그렇게 어렵지 않게 이해할 수 있습니다. 
#그러나 실제로 문제를 풀다보면 잘 못하는 경우가 굉장히 많습니다. 
#그런 사태를 미연에 방지하기 위해 한번 도전해 보도록 합시다.

In [ ]:
#numpy_lab.py 코드 구조
#본 Lab은 Numpy의 실행 방법을 이해하기 위해 8개의 함수를 작성해야 합니다. 
#각 함수별 구체적인 작성 방법은 아래와 같습니다. 단
#본 랩은 for loop을 사용할 경우, 틀린 걸로 처리합니다. 반드시 numpy 로만 처리하시기 바랍니다.

In [ ]:
# n_size_ndarray_creation
# Template
# def n_size_ndarray_creation(n, dtype=np.int):
#    X = None
#    return X

# 함수목적
# n의 제곱수로 2 dimentional array를 생성하는 ndarray.

# Args
# n: 생성하고자 하는 ndarray의 row와 column의 개수
# dtype: 생성하려는 ndarray의 data type (np.int)

# Returns
# row와 column의 길이가 n인 two dimentional ndarray로 X[0,0]은 0으로 순차적으로 X[n-1,n-1]은 n^2-1이 할당됨

In [1]:
import numpy as np

In [5]:
def n_size_ndarray_creation(n, dtype=np.int):
    return np.array(range(n**2),dtype=dtype).reshape(n,n)

n_size_ndarray_creation(3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
n=3
np.arange(n**2).reshape(n,n)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# zero_or_one_or_empty_ndarray
# Template
# def zero_or_one_or_empty_ndarray(shape, type=0, dtype=np.int):
#    X = None
#  return X

# 함수목적
# shape이 지정된 크기의 ndarray를 생성, 이때 행렬의 element는 type에 따라 0, 1 또는 empty로 생성됨.

# Args
# shape: 생성할려는 ndarray의 shape
# type: 생성되는 element들의 값을 지정함0은 0, 1은 1, 99는 empty 타입으로 생성됨
# dtype: 생성하려는 ndarray의 data type (np.int)

# Returns
# shape의 크기로 생성된 ndarray로 type에 따라 element의 내용이 변경됨

# Example
# >>> zero_or_one_or_empty_ndarray(shape=(2,2), type=1)
# array([[ 1,  1],
#        [ 1,  1]])
# >>> zero_or_one_or_empty_ndarray(shape=(3,3), type=99)
    #임의의수 생성
#array([[1773984320,        487, 1774114944],
#        [       487, 1947927088,          0],
#        [1947927088,          0, 1701605485]])

In [6]:
def zero_or_one_or_empty_ndarray(shape, type =0, dtype=np.int):
    if type == 0 :
        return np.zeros(shape= shape,dtype =dtype)
    if type == 1 :
        return np.ones(shape = shape,dtype =dtype)
    if type == 99 :
        return np.empty(shape = shape, dtype= dtype)

zero_or_one_or_empty_ndarray((3,3),0)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [4]:
np.ones((32,32), dtype=np.int)

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [ ]:
# change_shape_of_ndarray

# Template
# def change_shape_of_ndarray(X, n_row):
#    return X

# 함수목적
# 입력된 ndarray X를 n_row의 값을 row의 개수로 지정한 matrix를 반환함.
# 이때 입력하는 X의 size는 2의 거듭제곱수로 전제함.
# 만약 n_row과 1일 때는 matrix가 아닌 vector로 반환함.

# Args
# X: 입력하는 ndarray
# n_row: 생성할려는 matrix의 row의 개수

# Returns
# row의 개수가 n_row인 Matrix 또는 Vector
# n_row가 1이면 Vector 값으로 반환함

# Examples
# >>> import numpy as np
# >>> import numpy_lab as testcode
# >>> X = np.ones((32,32), dtype=np.int)
# >>> testcode.change_shape_of_ndarray(X, 1)
# array([1, 1, 1, ..., 1, 1, 1])
# >>> testcode.change_shape_of_ndarray(X, 512)
# array([[1, 1],
#       [1, 1],
#       [1, 1],
#       ...,
#       [1, 1],
#       [1, 1],
#       [1, 1]])

In [9]:
def change_shape_of_ndarray(X, n_row) :
    return X.flatten() if n_row == 1 else X.reshape(n_row,-1)

X = np.ones((4,4),dtype=np.int)
change_shape_of_ndarray(X,2)

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

In [ ]:
# concat_ndarray

# Template
# def concat_ndarray(X_1, X_2, axis):
#    pass

# 함수목적
# 입력된 ndarray X_1과 X_2를 axis로 입력된 축을 기준으로 통합하여 반환하는 함수
# X_1과 X_2는 matrix 또는 vector 임, 그러므로 vector 일 경우도 처리할 수 가 있어야 함
# axis를 기준으로 통합할 때, 통합이 불가능하면 False가 반환됨.
# 단 X_1과 X_2 Matrix, Vector 형태로 들어왔다면, Vector를 row가 1개인 Matrix로 변환하여 통합이 가능한지 확인할 것

# Args
# X_1: 입력하는 ndarray
# X_2: 입력하는 ndarray
# axis: 통합의 기준이 되는 축 0 또는 1임

# Returns
# X_1과 X_2과 통합된 matrix 타입의 ndarray

# Examples
# >>> import numpy as np
# >>> import numpy_lab as testcode
# >>> a = np.array([[1, 2], [3, 4]])
# >>> b = np.array([[5, 6]])
# >>> testcode.concat_ndarray(a, b, 0)
# array([[1, 2],
#       [3, 4],
#       [5, 6]])
# >>> testcode.concat_ndarray(a, b, 1)
# False
# >>> a = np.array([1, 2])
# >>> b = np.array([5, 6, 7])
# >>> testcode.concat_ndarray(a, b, 1)
# array([[1, 2, 5, 6, 7]])
# >>> testcode.concat_ndarray(a, b, 0)
# False

In [15]:
def concat_ndarray(X_1,X_2, axis):
    try :
        if X_1.ndim == 1 :
            X_1.reshape(1,-1)
        if X_2.ndim == 1 :
            X_2.reshape(1,-1)
        return np.concatenate((X_1,X_2),axis =axis)
    except ValueError as e:
        return False

a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
concat_ndarray(a,b ,0)
            

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# nomalize_ndarray
# Template
# def normalize_ndarray(X, axis=99, dtype=np.float32):
#    pass

# 함수목적
# 입력된 Matrix 또는 Vector를 ndarray X의 정규화된 값으로 변환하여 반환함
# 이때 정규화 변환 공식 Z = (X - X의평균) / X의 표준편차로 구성됨.
# X의 평균과 표준편차는 axis를 기준으로 axis 별로 산출됨.
# Matrix의 경우 axis가 0 또는 1일 경우, row 또는 column별로 Z value를 산출함.
# axis가 99일 경우 전체 값에 대한 normalize 값을 구함.

# Args
# X: 입력하는 ndarray,
# axis: normalize를 구하는 기준이 되는 축으로 0, 1 또는 99임, 단 99는 axis 구분 없이 전체값으로 평균과 표준편차를 구함
# dtype: data type으로 np.float32로 구정

# Returns
# 정규화된 ndarray

# Examples
# >>> import numpy as np
# >>> import numpy_lab as testcode
# >>> X = np.arange(12, dtype=np.float32).reshape(6,2)
# >>> testcode.normalize_ndarray(X)
# array([[-1.59325504, -1.3035723 ],
#       [-1.01388955, -0.72420681],
#       [-0.43452409, -0.14484136],
#       [ 0.14484136,  0.43452409],
#       [ 0.72420681,  1.01388955],
#       [ 1.3035723 ,  1.59325504]], dtype=float32)
# >>> testcode.normalize_ndarray(X, 1)
# array([[-1.,  1.],
#       [-1.,  1.],
#       [-1.,  1.],
#       [-1.,  1.],
#       [-1.,  1.],
#       [-1.,  1.]], dtype=float32)
# >>> testcode.normalize_ndarray(X, 0)
# array([[-1.46385002, -1.46385002],
#       [-0.87831002, -0.87831002],
#       [-0.29277   , -0.29277   ],
#       [ 0.29277   ,  0.29277   ],
#       [ 0.87831002,  0.87831002],
#       [ 1.46385002,  1.46385002]], dtype=float32)

In [28]:
def nomalize_ndarray(X, axis =99, dtype=np.float32):
    X = X.astype(np.float32)
    n_row,n_column = X.shape
    if axis == 99 : # 전체 표준화
        x_mean = np.mean(X)
        x_std = np.std(X)
        Z = (X-x_mean)/x_std
    if axis == 0 : 
        x_mean = np.mean(X,0).reshape(n_row,-1)
        x_std = np.std(X,0).reshape(n_row,-1)
        Z = (X-x_mean)/x_std
    if axis == 1 :
        x_mean = np.mean(X,1).reshape(n_row,-1)
        x_std = np.std(X,1).reshape(n_row,-1)
        Z = (X-x_mean)/x_std
    return Z

X = np.arange(12,dtype=np.float32).reshape(4,3)
print(X)
nomalize_ndarray(X,axis=1)
        

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


array([[-1.2247448,  0.       ,  1.2247448],
       [-1.2247448,  0.       ,  1.2247448],
       [-1.2247448,  0.       ,  1.2247448],
       [-1.2247448,  0.       ,  1.2247448]], dtype=float32)

In [ ]:
# boolean_index

# Template
# def boolean_index(X, condition):
#  pass

# 함수목적
# 입력된 ndarray X를 String type의 condition 정보를 바탕으로 해당 컨디션에 해당하는 ndarray X의 index 번호를 반환함
# 단 이때, str type의 조건인 condition을 코드로 변환하기 위해서는 eval(str("X") + condition)를 사용할 수 있음

# Args
# X: 입력하는 ndarray
# condition: string type의 조건 (">3", "== 5", "< 15")

# Returns
# 조건에 만족하는 ndarray X의 index

# Examples
# >>> import numpy as np
# >>> import numpy_lab as testcode
# >>> X = np.arange(32, dtype=np.float32).reshape(4, -1)
# >>> testcode.boolean_index(X, "== 3")
# (array([0]), array([3]))
# >>> X = np.arange(32, dtype=np.float32)
# >>> testcode.boolean_index(X, "> 6")
# (array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
#        23, 24, 25, 26, 27, 28, 29, 30, 31]),)

In [32]:
def boolean_index(X,condition):
    condition = eval(str("X") +condition)
    return np.where(condition)

X = np.arange(32,dtype = np.float32)
boolean_index(X,">6")

(array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23,
        24, 25, 26, 27, 28, 29, 30, 31], dtype=int64),)

In [ ]:
# find_nearest_value

# Template
# def find_nearest_value(X, target_value):
#    pass

# 함수목적
# 입력된 vector type의 ndarray X에서 target_value와 가장 차이가 작게나는 element를 찾아 리턴함
# 이때 X를 list로 변경하여 처리하는 것은 실패로 간주함.

# Args
# X: 입력하는 vector type의 ndarray
# target_value : 가장 유사한 값의 기준값이 되는 값

# Returns
# target_value와 가장 유사한 값

# Examples
# >>> import numpy as np
# >>> import numpy_lab as testcode
# >>> X = np.random.uniform(0, 1, 100)
# >>> target_value = 0.3
# >>> testcode.find_nearest_value(X, target_value)
# 0.29260674329282488 # 출력되는 값은 random 하게 바뀜

In [34]:
def find_nearest_value(X,target_value):
    return X[np.argmin(np.abs(X-target_value))]
X = np.random.uniform(0,1,5)
target_value = 0.3
print(X)
find_nearest_value(X,target_value)

[0.45422476 0.73400768 0.61490421 0.17346619 0.09628614]


0.17346619477562597

In [ ]:
# get_n_largest_values

# Template
#def get_n_largest_values(X, n):
#    pass

# 함수목적
# 입력된 vector type의 ndarray X에서 큰 숫자 순서대로 n개의 값을 반환함.

# Args
# X: vector type의 ndarray
# n: 반환할려는 element의 개수

# Returns
# ndarray X의 element중 큰 숫자 순서대로 n개 값이 반환됨 ndarray

# Examples
# >>> import numpy as np
# >>> import numpy_lab_solution as t
# >>> X = np.random.uniform(0, 1, 100)
# >>> t.get_n_largest_values(X, 3)
# array([ 0.98935239,  0.98494578,  0.98317255])
# >>> t.get_n_largest_values(X, 5)
# array([ 0.98935239,  0.98494578,  0.98317255,  0.96859596,  0.96485649])
# 출력되는 값은 random 하게 바뀜

In [47]:
def get_n_largest_values(X,n):
    X = X.astype(np.float32)
    return X[np.argsort(X)[::-1][:3]]
X = np.random.uniform(0,10,10)
get_n_largest_values(X,3)

array([8.768683, 8.505839, 5.993358], dtype=float32)

In [ ]:
# Lab - Build a matrix
#Introduction
# 두 번째 랩은 Pandas와 Numpy를 활용하여 Rating Matrix 또는 Frequent Matrix를 만드는 것입니다. 
# 추천 시스템 개발 등 머신러닝을 하다 보면 누가, 어떤 물건(또는 서비스)를 얼마나 이용하고 평가 하였는 가를 
# Matrix 형태로 변형하여 분석하는 일이 많은데 이를 위한 전처리 과정이 필요합니다. 
# 흔한 예제로 생각해보면 영화를 본 사용자들이 각 영화를 평가한 별점 점수를 Matrix 형태로 표현하는 것이 있습니다. 
# 일반적으로 데이터 베이스는 저장 공간의 효율성을 위해 Matrix 형태로 저장하는 것이 아니라 Event과 발생한 정보를 Row 단위로 저장합니다. 
# 이렇게 DB에 쌓인 정보를 Matrix로 변환하는 게 이번 랩의 목표입니다. 실제 데이터의 변환은 아래 그림과 같습니다.

In [ ]:
# bulid_matrix.py 코드 구조
# 본 Lab은 Pandas의 기본적인 동작과 Numpy를 결합하여 일반적으로 쌓여있는 데이터를 Matrix 형태로 변경합니다. 
# 변환되는 Matrix 형태는 두가지이며, 본 Lab도 두 가지 모두를 지원하는 것을 목표로 합니다.

In [ ]:
# get_rating_matrix
# 첫 번째 함수는 Rating Matix을 만드는 것 입니다. 
# Rating Matrix는 영화, 책 처럼 사용자가 제품에 대한 평가를 Matrix 형태로 표현한 것입니다. 
# 저희는 movie_rating.csv라는 파일을 활용하여 rating matrix를 구성한다. movie_rating.csv는 아래처럼 구성된다.
# 본 랩에서 다루는 모든 csv파일의 column은 source, target으로 구성되며, source는 row의 index 정보가, target는 column의 기준 정보가 된다. 
# rating 정보는 get_rating_matrix 함수에서만 사용되며, 사용자가 영화에 대한 평가를 정보를 담고 있다.

In [ ]:
# 본 랩의 목적은 위 테이블과 같이 구성된 정보를 Matrix 형태로 바꾸는 거다. Matrix 형태로 바꾸는 규칙은 다음과 같다.
# source는 row, target은 column의 기준이 된다.
# source와 target의 정렬된 값을 활용하여 index를 설정한다. 즉 위 Table에서는 Claudia Puig과 row의 0번째 index로 설정된다.
# rating의 정보는 Matrix에서 각 Element 값에 할당된다.
# 생성되는 Matrix Ndarray로 나타난다.
# dict, collection 모듈 등 파이썬의 Built-in Module은 사용할 수 있으나, for 문은 사용할 수 없다.

# 생성하는 함수의 Template은 아래와 같으며, 입력값은 처리하는 csv 파일의 이름만 넣을 수 있다.
# def get_rating_matrix(filename):
#    pass

In [ ]:
# 실제한 구현한 예제와 결과물은 아래와 같다.

# >>> import numpy as np
# >>> import build_matrix as test_code
# >>> test_code.get_rating_matrix("movie_rating.csv")
# array([[ 3. ,  0. ,  3.5,  0. ,  4.5,  0. ],
#       [ 0. ,  3. ,  3.5,  0. ,  3. ,  3.5],
#       [ 0. ,  3. ,  4. ,  5. ,  3. ,  3.5],
#       [ 3. ,  2.5,  3.5,  3.5,  3. ,  2.5],
#       [ 2. ,  3. ,  4. ,  3. ,  3. ,  0. ],
#       [ 0. ,  0. ,  4.5,  4. ,  0. ,  0. ]], dtype=float32)

In [48]:
import numpy as np
import pandas as pd

In [62]:
def get_rating_matrix(filename, dtype=np.float32):
    df = pd.read_csv(filename)
    return df.groupby(["source","target"])["rating"].sum().unstack().fillna(0) 
    # unstack을 통해서 매트릭스화 한다음 na 값을 0으로 채움

filename = "./movie_rating.csv"
get_rating_matrix(filename)

target         Just My Luck  Lady in the Water  Snakes on a Plane  \
source                                                              
Claudia Puig            3.0                0.0                3.5   
Gene Seymour            0.0                3.0                3.5   
Jack Matthews           0.0                3.0                4.0   
Lisa Rose               3.0                2.5                3.5   
Mick LaSalle            2.0                3.0                4.0   
Toby                    0.0                0.0                4.5   

target         Superman Returns  The Night Listener  You Me and Dupree  
source                                                                  
Claudia Puig                0.0                 4.5                0.0  
Gene Seymour                0.0                 3.0                3.5  
Jack Matthews               5.0                 3.0                3.5  
Lisa Rose                   3.5                 3.0                2.5  
Mick LaSalle                3.0                 3.0                0.0  
Toby                        4.0                 0.0                0.0

In [ ]:
# get_frequent_matrix
# 두 번째 함수는 얼마나 빈번하게 제품을 구매했는지를 표현하는 Frequent Matrix를 만드는 것 입니다. 
# Frequent Matrix는 사용자가 특정 제품을 구매한 횟수를 기록하는 Matrix이다. 
# 저희가 제공하는 csv파일은 1000i.csv라는 파일로 아래처럼 구성되어 있습니다.

In [ ]:
# 본 함수에서는 기존 함수와 달리 Rating column이 없습니다. 
# 대신 source와 target의 조합이 한 개 이상으로 중복될 수 있고, 이것이 Frequent로 처리해야 합니다. 
# 즉 Rating이 명시적으로 있는게 아니라 데이터를 통해 Frequent를 찾아내는 것이 목적입니다. Matrix 형태로 바꾸는 규칙은 다음과 같습니다.

# source는 row, target은 column의 기준이 된다.
# source와 target의 정렬된 값을 활용하여 index를 설정한다. 즉 위 Table에서는 1은 row의 0번째 index로 설정된다.
# Source와 Target이 출현한 정보는 Frequent로 Matrix에서 각 Element 값에 할당되어야 한다.
# 생성되는 Matrix Ndarray로 나타내며, dtype은 np.float32
# dict, collection 모듈 등 파이썬의 Built-in Module은 사용할 수 있으나, for 문은 사용할 수 없다.

In [ ]:
# 생성하는 함수의 Template은 아래와 같으며, 입력값은 처리하는 csv 파일의 이름만 넣을 수 있다.

# def get_frequent_matrix(filename):
#    pass

In [ ]:
# 실제한 구현한 예제와 결과물은 아래와 같다.

# >>> import numpy as np
# >>> import build_matrix as test_code
# >>> test_code.get_frequent_matrix("1000i.csv")
# array([[ 19.,  17.,  14.,  11.,  17.,  25.,   7.,  22.,   5.,  18.,  10.,
#         13.,  13.,   8.,  20.,  10.,   9.,  10.,  16.,  15.,   9.,  11.,
#         17.,  15.,  14.,   8.,   6.,  12.,  18.,  12.,   6.,  18.,   9.,
#         24.,   7.,  19.,  14.,   6.,   4.,  12.,  15.,  14.,  20.,   9.,
#         12.,  16.,  11.,   9.,  11.,  12.],
#       [ 20.,  16.,  10.,  15.,  17.,  18.,  10.,  13.,   5.,  19.,   8.,
#         14.,  14.,   9.,  15.,  14.,  13.,   8.,  12.,   9.,   5.,  10.,
#         28.,  18.,   7.,   8.,   6.,  19.,  14.,  13.,  11.,  12.,  18.,
#         15.,   7.,  11.,  17.,   9.,   5.,   5.,  13.,  12.,  15.,   9.,
#         13.,  16.,  16.,  10.,  16.,   9.],
#       [ 12.,  16.,  13.,  19.,  23.,  19.,   5.,  14.,   5.,  18.,   7.,
#          6.,  14.,   8.,  20.,  17.,  14.,  11.,  16.,  12.,   7.,   9.,
#         23.,  12.,  12.,   8.,   7.,  23.,  26.,  10.,   9.,  20.,  16.,
#         11.,   4.,  19.,  12.,  12.,   5.,  10.,  10.,  14.,  10.,  17.,
#         15.,  16.,  11.,  17.,   9.,  11.],
#       [ 14.,  14.,  19.,  11.,  11.,  18.,   7.,  16.,   7.,  17.,   6.,
#         19.,  18.,  12.,  13.,  13.,  14.,   9.,  21.,  16.,   6.,   6.,
#         19.,  14.,  19.,   5.,  12.,  14.,  18.,  11.,  11.,  21.,  15.,
#         10.,  11.,  14.,  17.,  21.,   6.,  14.,   9.,  16.,  18.,  12.,
#         16.,  16.,  26.,  16.,  12.,  20.],
#       [ 13.,   7.,   8.,  15.,  13.,  16.,   3.,  19.,  11.,  12.,   7.,
#         10.,  13.,  14.,  16.,  14.,  23.,   9.,  13.,  10.,  11.,   3.,
#         11.,  14.,   9.,   6.,  11.,  16.,  18.,  11.,   5.,  14.,  10.,
#         16.,  10.,   5.,  14.,  11.,   3.,   9.,  11.,  10.,  16.,   8.,
#         13.,  20.,  14.,  18.,  21.,   3.]], dtype=float32)

In [73]:
def get_frequent_matrix(filename, dtype = np.float32):
    df = pd.read_csv(filename)
    df["rating"] = 1
    return df.groupby(["source","target"])["rating"].sum().unstack().fillna(0)  
    # 중복된 값을 인정하는 것임 예를 들면 상품에 대한 클릭횟수(구매선호도)

filename = "./1000i.csv"
get_frequent_matrix(filename)

target  0   1   2   3   4   5   6   7   8   9   ...  40  41  42  43  44  45  \
source                                          ...                           
1       19  17  14  11  17  25   7  22   5  18  ...  15  14  20   9  12  16   
2       20  16  10  15  17  18  10  13   5  19  ...  13  12  15   9  13  16   
3       12  16  13  19  23  19   5  14   5  18  ...  10  14  10  17  15  16   
4       14  14  19  11  11  18   7  16   7  17  ...   9  16  18  12  16  16   
5       13   7   8  15  13  16   3  19  11  12  ...  11  10  16   8  13  20   

target  46  47  48  49  
source                  
1       11   9  11  12  
2       16  10  16   9  
3       11  17   9  11  
4       26  16  12  20  
5       14  18  21   3  

[5 rows x 50 columns]

In [ ]:
# Case Study - AirPassengers 

In [2]:
import pandas as pd
import numpy as np

In [127]:
df_time_series = pd.read_csv("./AirPassengers.csv")
df_time_series.head()

Month  #Passengers
0  Jan-49          112
1  Feb-49          118
2  Mar-49          132
3  Apr-49          129
4  May-49          121

In [128]:
df_time_series["step"] = range(len(df_time_series))
df_time_series.head()

Month  #Passengers  step
0  Jan-49          112     0
1  Feb-49          118     1
2  Mar-49          132     2
3  Apr-49          129     3
4  May-49          121     4

In [129]:
df_time_series["cum_sum"] = df_time_series["#Passengers"].cumsum()
df_time_series["cum_max"] = df_time_series["#Passengers"].cummax()
df_time_series["cum_min"] = df_time_series["#Passengers"].cummin()
df_time_series.head()

Month  #Passengers  step  cum_sum  cum_max  cum_min
0  Jan-49          112     0      112      112      112
1  Feb-49          118     1      230      118      112
2  Mar-49          132     2      362      132      112
3  Apr-49          129     3      491      132      112
4  May-49          121     4      612      132      112

In [130]:
import numpy as np
temp_date = df_time_series["Month"].map(lambda x : x.split("-"))

In [131]:
temp_date = np.array(temp_date.values.tolist())
temp_date[:5]

array([['Jan', '49'],
       ['Feb', '49'],
       ['Mar', '49'],
       ['Apr', '49'],
       ['May', '49']], dtype='<U3')

In [132]:
df_time_series["year"] = temp_date[:, 1]
df_time_series["month"] = temp_date[:, 0]

In [133]:
df_time_series.head()

Month  #Passengers  step  cum_sum  cum_max  cum_min year month
0  Jan-49          112     0      112      112      112   49   Jan
1  Feb-49          118     1      230      118      112   49   Feb
2  Mar-49          132     2      362      132      112   49   Mar
3  Apr-49          129     3      491      132      112   49   Apr
4  May-49          121     4      612      132      112   49   May

In [134]:
df_time_series["diff"] = df_time_series["#Passengers"].diff().fillna(0)
df_time_series[:5]

Month  #Passengers  step  cum_sum  cum_max  cum_min year month  diff
0  Jan-49          112     0      112      112      112   49   Jan   0.0
1  Feb-49          118     1      230      118      112   49   Feb   6.0
2  Mar-49          132     2      362      132      112   49   Mar  14.0
3  Apr-49          129     3      491      132      112   49   Apr  -3.0
4  May-49          121     4      612      132      112   49   May  -8.0

In [135]:
df_time_series['year'] = '19' + df_time_series["year"].values 

In [136]:
df_time_series['month'].unique()

array(['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep',
       'Oct', 'Nov', 'Dec'], dtype=object)

In [137]:
df_time_series["month"] = np.where(df_time_series["month"]=='Jan', '01', df_time_series["month"]) 

In [138]:
df_time_series["month"] = np.where(df_time_series["month"]=='Feb', '02', df_time_series["month"]) 

In [139]:
df_time_series["month"] = np.where(df_time_series["month"]=='Mar', '03', df_time_series["month"])

In [140]:
df_time_series["month"] = np.where(df_time_series["month"]=='Apr', '04', df_time_series["month"]) 

In [141]:
df_time_series["month"] = np.where(df_time_series["month"]=='May', '05', df_time_series["month"]) 

In [142]:
df_time_series["month"] = np.where(df_time_series["month"]=='Jun', '06', df_time_series["month"]) 

In [143]:
df_time_series["month"] = np.where(df_time_series["month"]=='Jul', '07', df_time_series["month"]) 

In [144]:
df_time_series["month"] = np.where(df_time_series["month"]=='Aug', '08', df_time_series["month"]) 

In [145]:
df_time_series["month"] = np.where(df_time_series["month"]=='Sep', '09', df_time_series["month"]) 

In [146]:
df_time_series["month"] = np.where(df_time_series["month"]=='Oct', '10', df_time_series["month"]) 

In [147]:
df_time_series["month"] = np.where(df_time_series["month"]=='Nov', '11', df_time_series["month"]) 

In [148]:
df_time_series["month"] = np.where(df_time_series["month"]=='Dec', '12', df_time_series["month"]) 

In [156]:
df_time_series.head()

Month  #Passengers  step  cum_sum  cum_max  cum_min  year month  diff  \
0  Jan-49          112     0      112      112      112  1949    01   0.0   
1  Feb-49          118     1      230      118      112  1949    02   6.0   
2  Mar-49          132     2      362      132      112  1949    03  14.0   
3  Apr-49          129     3      491      132      112  1949    04  -3.0   
4  May-49          121     4      612      132      112  1949    05  -8.0   

     pct  
0    nan  
1   5.36  
2  11.86  
3  -2.27  
4  -6.20

In [150]:
df_time_series["#Passengers"].pct_change().map(lambda x : x*100).map(lambda x : " %.2f" % x) 
# pct_cahnge() : 이전 값 대비 percentage 변동률
# 보기 좋게 하기 위해 *100 을 하고 또한 소수점 둘째자리 까지만 보이게함

0          nan
1         5.36
2        11.86
3        -2.27
4        -6.20
5        11.57
6         9.63
7         0.00
8        -8.11
9       -12.50
10      -12.61
11       13.46
12       -2.54
13        9.57
14       11.90
15       -4.26
16       -7.41
17       19.20
18       14.09
19        0.00
20       -7.06
21      -15.82
22      -14.29
23       22.81
24        3.57
25        3.45
26       18.67
27       -8.43
28        5.52
29        3.49
        ...   
114      12.87
115       2.85
116     -20.00
117     -11.14
118     -13.65
119       8.71
120       6.82
121      -5.00
122      18.71
123      -2.46
124       6.06
125      12.38
126      16.10
127       2.01
128     -17.17
129     -12.10
130     -11.06
131      11.88
132       2.96
133      -6.24
134       7.16
135      10.02
136       2.39
137      13.35
138      16.26
139      -2.57
140     -16.17
141      -9.25
142     -15.40
143      10.77
Name: #Passengers, Length: 144, dtype: object

In [155]:
df_time_series["pct"]= df_time_series["#Passengers"].pct_change().map(lambda x: "%.2f" % (x * 100))

In [157]:
df_time_series.groupby(["year"]).sum()

#Passengers  step  cum_sum  cum_max  cum_min  diff
year                                                    
1949         1520    66     9891     1649     1328   6.0
1950         1676   210    28943     1909     1248  22.0
1951         2042   354    51480     2246     1248  26.0
1952         2364   498    77974     2653     1248  28.0
1953         2700   642   108826     3077     1248   7.0
1954         2867   786   141888     3444     1248  28.0
1955         3408   930   179692     4009     1248  49.0
1956         3939  1074   224217     4672     1248  28.0
1957         4421  1218   274497     5287     1248  30.0
1958         4572  1362   328644     5818     1248   1.0
1959         5140  1506   386763     6373     1248  68.0
1960         5714  1650   452342     7086     1248  27.0

In [160]:
# Case Study - Patent Data

patent = pd.read_csv("https://raw.githubusercontent.com/TEAMLAB-Lecture/AI-python-connect/master/codes/ch_3/part-1/data/sea_managing_raw.csv",encoding="cp949")
patent.head()

국가코드 DB종류 특허/실용 구분 문헌종류 코드  \
0   US   US        P      B2   
1   US   US        P      A1   
2   US   US        P      A1   
3   US   US        P      A1   
4   US   US        P      B2   

                                              발명의 명칭  \
0                      Turboengine water wash system   
1  TREATMENT OF TAILINGS WITH DEIONIZED SILICATE ...   
2  Method And Apparatus For Treating Tailings Usi...   
3   METHOD FOR STABILIZING WASTE AND HAZARDOUS WASTE   
4  Water treatment process and plant using ballas...   

                                                  요약  \
0  A system for cleaning gas turbine engines is d...   
1  A process for treating a tailings stream compr...   
2  There is a method described of treating tailin...   
3  The invention provides a process for stabilizi...   
4  A method for treating wastewater using a balla...   

                                               대표청구항  청구항 수       출원번호  \
0  1. An apparatus for cleaning wing mounted gas ...     64  11/644784   
1  1. A process for treating a tailings stream co...     20  13/848244   
2  1. A method of treating tailings having a comb...     18  13/765924   
3  1. A method for stabilizing hazardous waste, c...     20  13/767408   
4  1. A method of treating wastewater including: ...     18  12/521154   

          출원일  ... Original CPC Main              Original CPC All  \
0  2006-12-22  ...               NaN                           NaN   
1  2013-03-21  ...    B09B-0003/0025                B09B-0003/0025   
2  2013-02-13  ...      C02F-0001/48                  C02F-0001/48   
3  2013-02-14  ...      A62D-0003/33  A62D-0003/33 | G21F-0009/302   
4  2007-12-26  ...               NaN                           NaN   

  Original IPC Main                                   Original IPC All  \
0       B08B-009/00                                        B08B-009/00   
1       B09B-003/00                                        B09B-003/00   
2       C02F-001/48                                        C02F-001/48   
3       A62D-003/33                          A62D-003/33 | G21F-009/30   
4       C02F-001/52  C02F-001/52 | B01D-021/01 | B01D-021/02 | B01D...   

  Original US Class Main[US]  \
0                  134/166.R   
1                    106/627   
2                    204/554   
3                    588/002   
4                    210/709   

                           Original US Class All[US]  Original FI[JP]  \
0                                134/166.R | 134/138              NaN   
1  106/627 | 106/600 | 106/631 | 106/632 | 106/63...              NaN   
2                                            204/554              NaN   
3                                  588/002 | 588/315              NaN   
4  210/709 | 210/711 | 210/712 | 210/713 | 210/71...              NaN   

  Original F-term[JP] Original Theme Code [JP]   WIPS ON key  
0                 NaN                      NaN  4.914000e+12  
1                 NaN                      NaN  5.414000e+12  
2                 NaN                      NaN  5.414000e+12  
3                 NaN                      NaN  5.414000e+12  
4                 NaN                      NaN  4.913050e+12  

[5 rows x 37 columns]

In [161]:
patent["출원번호"].isnull().sum()

0

In [163]:
df_patent = patent[["출원번호","Original US Class All[US]"]]
df_patent

출원번호                          Original US Class All[US]
0     11/644784                                134/166.R | 134/138
1     13/848244  106/627 | 106/600 | 106/631 | 106/632 | 106/63...
2     13/765924                                            204/554
3     13/767408                                  588/002 | 588/315
4     12/521154  210/709 | 210/711 | 210/712 | 210/713 | 210/71...
5     13/915506                        210/636 | 210/189 | 210/638
6     13/955538                                  053/434 | 053/436
7     12/966723    405/286 | 405/284 | 047/044 | 047/047 | 047/083
8     11/596068    604/368 | 524/300 | 524/322 | 588/249 | 588/255
9     13/981662                                            210/609
10    13/836061  210/741 | 210/109 | 210/103 | 210/117 | 210/74...
11    13/939857                      210/747.9 | 210/109 | 210/117
12    13/944223  422/004 | 315/294 | 362/249.02 | 422/024 | 210...
13    12/924981                        248/534 | 248/530 | 052/296
14    13/994340                                  210/648 | 210/188
15    13/811380  210/634 | 210/096.1 | 210/767 | 210/787 | 210/...
16    12/816160            210/739 | 210/767 | 210/800 | 210/198.1
17    13/588215    210/605 | 210/614 | 210/623 | 210/626 | 210/628
18    12/860030           210/610 | 210/620 | 210/170.06 | 136/244
19    13/761140  048/204 | 048/102.R | 048/127.9 | 203/047 | 20...
20    13/863745                                            210/631
21    13/814126    210/614 | 210/205 | 210/102 | 210/097 | 210/620
22    13/411298                                          405/302.7
23    13/418840                                          405/302.7
24    13/761140                        201/006 | 201/020 | 202/099
25    13/747460                                405/270 | 405/302.7
26    13/748486              524/060 | 524/547 | 524/446 | 526/240
27    13/735673                                  204/571 | 204/660
28    12/814377                        210/681 | 210/687 | 106/713
29    13/720960                  210/710 | 210/170.09 | 210/170.05
...         ...                                                ...
1875  09/576877                        435/262 | 209/930 | 241/028
1876  09/872990                                            210/766
1877  10/157507                405/129.2 | 405/129.25 | 405/129.45
1878  09/298407    405/129.95 | 405/128.15 | 405/129.1 | 405/128.7
1879  10/102392                                  210/610 | 210/747
1880  10/151762                                            037/307
1881  10/094064                        037/317 | 707/517 | 707/530
1882  09/989192                                            210/660
1883  09/692788  405/129.9 | 405/129.95 | 405/129.45 | 405/129....
1884  09/987234                                            210/749
1885  09/653691  210/636 | 210/639 | 210/641 | 210/651 | 210/72...
1886  09/483378                                047/058.1 | 047/009
1887  10/041258  166/250.07 | 166/263 | 166/311 | 166/312 | 405...
1888  09/948969                                  075/712 | 800/295
1889  09/770123  210/710 | 210/712 | 210/716 | 210/723 | 210/73...
1890  09/907519    210/605 | 210/151 | 210/220 | 210/259 | 210/631
1891  09/783297                             405/129.5 | 405/129.95
1892  09/823026    210/634 | 210/774 | 210/747 | 210/808 | 175/066
1893  09/968997                                  588/228 | 431/002
1894  09/883718              210/759 | 210/766 | 210/768 | 210/774
1895  09/809396                                  208/428 | 208/435
1896  09/770123                        252/175 | 252/184 | 502/400
1897  09/815766              210/764 | 210/770 | 210/790 | 210/181
1898  09/356273  588/256 | 405/129.25 | 405/129.65 | 405/129.95...
1899  09/729291                                            702/006
1900  09/389673                        075/398 | 075/399 | 075/711
1901  09/045188    210/688 | 210/747 | 210/912 | 588/001 | 588/020
1902  09/151716                        588/257 | 588/252 |

In [164]:
df_patent["Original US Class All[US]"][:5]

0                                  134/166.R | 134/138
1    106/627 | 106/600 | 106/631 | 106/632 | 106/63...
2                                              204/554
3                                    588/002 | 588/315
4    210/709 | 210/711 | 210/712 | 210/713 | 210/71...
Name: Original US Class All[US], dtype: object

In [165]:
df_patent["Original US Class All[US]"].map(lambda x : x.split("|")).tolist()

[['134/166.R ', ' 134/138'],
 ['106/627 ', ' 106/600 ', ' 106/631 ', ' 106/632 ', ' 106/634 ', ' 210/702'],
 ['204/554'],
 ['588/002 ', ' 588/315'],
 ['210/709 ',
  ' 210/711 ',
  ' 210/712 ',
  ' 210/713 ',
  ' 210/714 ',
  ' 210/724 ',
  ' 210/726 ',
  ' 210/738 ',
  ' 210/739 ',
  ' 210/745'],
 ['210/636 ', ' 210/189 ', ' 210/638'],
 ['053/434 ', ' 053/436'],
 ['405/286 ', ' 405/284 ', ' 047/044 ', ' 047/047 ', ' 047/083'],
 ['604/368 ', ' 524/300 ', ' 524/322 ', ' 588/249 ', ' 588/255'],
 ['210/609'],
 ['210/741 ',
  ' 210/109 ',
  ' 210/103 ',
  ' 210/117 ',
  ' 210/747.9 ',
  ' 210/137'],
 ['210/747.9 ', ' 210/109 ', ' 210/117'],
 ['422/004 ', ' 315/294 ', ' 362/249.02 ', ' 422/024 ', ' 210/748.11'],
 ['248/534 ', ' 248/530 ', ' 052/296'],
 ['210/648 ', ' 210/188'],
 ['210/634 ',
  ' 210/096.1 ',
  ' 210/767 ',
  ' 210/787 ',
  ' 210/774 ',
  ' 210/772 ',
  ' 210/739 ',
  ' 210/202'],
 ['210/739 ', ' 210/767 ', ' 210/800 ', ' 210/198.1'],
 ['210/605 ', ' 210/614 ', ' 210/623 ', '

In [166]:
edge_list = []
for data in zip(df_patent["출원번호"].tolist() ,df_patent["Original US Class All[US]"].map(lambda x : x.split("|")).tolist()):
    for value in data[1]:
        edge_list.append([data[0], value.strip()]) #strip() 함수를 쓰게되면 양쪽 공백과 기호(\n)를 제거해줌 

In [168]:
edge_list[:10]

[['11/644784', '134/166.R'],
 ['11/644784', '134/138'],
 ['13/848244', '106/627'],
 ['13/848244', '106/600'],
 ['13/848244', '106/631'],
 ['13/848244', '106/632'],
 ['13/848244', '106/634'],
 ['13/848244', '210/702'],
 ['13/765924', '204/554'],
 ['13/767408', '588/002']]

In [170]:
df_edge_list = pd.DataFrame(edge_list)
df_edge_list

0           1
0     11/644784   134/166.R
1     11/644784     134/138
2     13/848244     106/627
3     13/848244     106/600
4     13/848244     106/631
5     13/848244     106/632
6     13/848244     106/634
7     13/848244     210/702
8     13/765924     204/554
9     13/767408     588/002
10    13/767408     588/315
11    12/521154     210/709
12    12/521154     210/711
13    12/521154     210/712
14    12/521154     210/713
15    12/521154     210/714
16    12/521154     210/724
17    12/521154     210/726
18    12/521154     210/738
19    12/521154     210/739
20    12/521154     210/745
21    13/915506     210/636
22    13/915506     210/189
23    13/915506     210/638
24    13/955538     053/434
25    13/955538     053/436
26    12/966723     405/286
27    12/966723     405/284
28    12/966723     047/044
29    12/966723     047/047
...         ...         ...
6343  09/356273  405/129.95
6344  09/356273     588/252
6345  09/356273     588/259
6346  09/729291     702/006
6347  09/389673     075/398
6348  09/389673     075/399
6349  09/389673     075/711
6350  09/045188     210/688
6351  09/045188     210/747
6352  09/045188     210/912
6353  09/045188     588/001
6354  09/045188     588/020
6355  09/151716     588/257
6356  09/151716     588/252
6357  09/151716     405/129
6358  09/238463     210/732
6359  09/238463     210/800
6360  09/238463     210/808
6361  09/238463     210/533
6362  09/238463     210/536
6363  09/238463     210/537
6364  09/238463     210/123
6365  09/238463     210/136
6366  09/238463     210/241
6367  09/238463     210/119
6368  09/089886     210/605
6369  09/089886     210/613
6370  09/089886     210/614
6371  09/089886     210/625
6372  09/089886     210/903

[6373 rows x 2 columns]

In [171]:
df_edge_list["rating"] = 1

In [174]:
df_edge_list.columns = ['출원번호',"Original US Class All[US]","rating"]

In [175]:
df_edge_list.groupby(["출원번호","Original US Class All[US]"])["rating"].sum().unstack().fillna(0)

Original US Class All[US]  004/114.1  004/144.1  004/222  004/459  004/679  \
출원번호                                                                         
05/583686                        0.0        0.0      0.0      0.0      0.0   
05/634273                        0.0        0.0      0.0      0.0      0.0   
05/636159                        0.0        0.0      0.0      0.0      0.0   
05/677447                        0.0        0.0      0.0      0.0      0.0   
05/701218                        0.0        0.0      0.0      0.0      0.0   
05/772460                        0.0        0.0      0.0      0.0      0.0   
05/801551                        0.0        0.0      0.0      0.0      0.0   
05/807560                        0.0        0.0      0.0      0.0      0.0   
05/809031                        0.0        0.0      0.0      0.0      0.0   
05/935641                        0.0        0.0      0.0      0.0      0.0   
05/935672                        0.0        0.0      0.0      0.0      0.0   
05/935673                        0.0        0.0      0.0      0.0      0.0   
06/014118                        0.0        0.0      0.0      0.0      0.0   
06/111812                        0.0        0.0      0.0      0.0      0.0   
06/153826                        0.0        0.0      0.0      0.0      0.0   
06/325778                        0.0        0.0      0.0      0.0      0.0   
06/364998                        0.0        0.0      0.0      0.0      0.0   
06/443529                        0.0        0.0      0.0      0.0      0.0   
06/466803                        0.0        0.0      0.0      0.0      0.0   
06/511329                        0.0        0.0      0.0      0.0      0.0   
06/556004                        0.0        0.0      0.0      0.0      0.0   
06/578352                        0.0        0.0      0.0      0.0      0.0   
06/587591                        0.0        0.0      0.0      0.0      0.0   
06/591701                        0.0        0.0      0.0      0.0      0.0   
06/607313                        0.0        0.0      0.0      0.0      0.0   
06/663271                        0.0        0.0      0.0      0.0      0.0   
06/705226                        0.0        0.0      0.0      0.0      0.0   
06/740506                        0.0        0.0      0.0      0.0      0.0   
06/781869                        0.0        0.0      0.0      0.0      0.0   
06/850862                        0.0        0.0      0.0      0.0      0.0   
...                              ...        ...      ...      ...      ...   
13/761140                        0.0        0.0      0.0      0.0      0.0   
13/765924                        0.0        0.0      0.0      0.0      0.0   
13/767408                        0.0        0.0      0.0      0.0      0.0   
13/776329                        0.0        0.0      0.0      0.0      0.0   
13/784342                        0.0        0.0      0.0      0.0      0.0   
13/801483                        0.0        0.0      0.0      0.0      0.0   
13/810839                        0.0        0.0      0.0      0.0      0.0   
13/811380                        0.0        0.0      0.0      0.0      0.0   
13/813754                        0.0        0.0      0.0      0.0      0.0   
13/814126                        0.0        0.0      0.0      0.0      0.0   
13/817594                        0.0        0.0      0.0      0.0      0.0   
13/836061                        0.0        0.0      0.0      0.0      0.0   
13/848244                        0.0        0.0      0.0      0.0      0.0   
13/863745                        0.0        0.0      0.0      0.0      0.0   
13/886135                        0.0        0.0      0.0      0.0      0.0   
13/915506                        0.0        0.0      0.0      0.0      0.0   
13/922755                        0.0        0.0      0.0      0.0      0.0   
13/939857                        0.0        0.0      0.0      0.0      0.0   
13/939901             